#!/bin/bash

set -e 

if [[ "$@" == "-h" || "$@" == "--help" ]]; then

    python3 cctrace.py --help
    exit 0
fi

# must run as root.
if [[ "$EUID" -ne 0 ]]; then 
    echo >&2 "Please run as root"; exit 1
fi

# check that sysdig is installed and working
if type "sysdig" > /dev/null 2>&1; then
  # older versions of sysdig does not have a --version flag, so use --help
  sysdig --help | grep -q "sysdig version 0.23" || \
    { echo >&2 "sysdig version 0.23 expected"; exit 1; }
else
    echo >&2 "Please make sure sysdig is installed"; exit 1
fi

if type "python3" > /dev/null 2>&1; then
    # TODO: check that python3 is v3 and check for packages
    true
else
    echo >&2 "Error, python3 not in path"; exit 1
fi

# UTF-8 output is required for non-ASCII tree render styles
if locale -a | grep --ignore-case --quiet en_US.utf8; then
    export LANG="en_US.UTF-8"
    export LC_ALL="en_US.UTF-8" # overrides all other LC_* variables
fi

FORMAT="%thread.tid#%evt.type#%proc.exepath#%proc.pname#%proc.pid#%proc.ppid"
FORMAT="$FORMAT#%proc.args#%evt.args##"
FILTER="(evt.type=execve or evt.type=clone or evt.type=procexit) and evt.failed=false and user.name=${USER}"
sysdig --print-base64 -p"$FORMAT" "${FILTER}" \
  | USER=$() python3 -u cctrace.py "$@"
