#!/bin/bash

set -e 

# must run as root.
if [[ "$EUID" -ne 0 ]]; then 
    echo >&2 "Please run as root"; exit 1
fi

# check that sysdig is installed and working
if type "sysdig" > /dev/null 2>&1; then
  sysdig --version | grep -q "sysdig version 0.21.0" || \
    { echo >&2 "sysdig version 0.21.0 expected"; exit 1; }
else
    echo >&2 "Please make sure sysdig is installed"; exit 1
fi

if type "python3" > /dev/null 2>&1; then
    # TODO: check that python3 is v3 and check for packages
    true
else 
    echo >&2 "Error, python3 not in path"; exit 1
fi

# UTF-8 output is required for non-ASCII tree render styles
if locale -a | grep --ignore-case --quiet en_US.utf8; then
    LANG="en_US.UTF-8"
    LC_ALL="en_US.UTF-8" # overrides all other LC_* variables
fi

FORMAT="%thread.tid#%evt.type#%proc.exepath#%proc.pname#%proc.pid#%proc.ppid"
FORMAT="$FORMAT#%proc.args#%evt.args##"
FILTER="evt.type=execve or evt.type=clone and evt.failed=false and user.name=$(logname)"
SYSDIG=sysdig
# SYSDIG=$HOME/sysdig/build/userspace/sysdig/sysdig
$SYSDIG --print-base64 -p"$FORMAT" $FILTER \
  | python3 cctrace.py
