name = "multicompiler"
on_error = "die" # options die|warn

[cc]
path = "~/selfrando-testing/local/bin/clang"

[cxx]
path = "~/selfrando-testing/local/bin/clang++"


[ld]
prefix = "~/selfrando-testing/local/bin"

